CREATE TABLE notification_library_notifications (
  id UUID PRIMARY KEY,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  notify_template_id TEXT NOT NULL,
  notify_notification_id TEXT,
  notify_status TEXT,
  notify_status_last_updated_at TIMESTAMPTZ,
  recipient TEXT NOT NULL,
  mail_merge_fields JSONB,
  domain_reference_id TEXT NOT NULL,
  domain_reference_type TEXT NOT NULL,
  log_correlation_id TEXT,
  requested_on TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  failure_reason TEXT,
  last_failed_at TIMESTAMPTZ,
  retry_count INT,
  last_send_attempt_at TIMESTAMPTZ
);

CREATE TABLE notification_library_notifications_aud (
  rev SERIAL,
  revtype NUMERIC,
  id UUID,
  type TEXT,
  status TEXT,
  notify_status_last_updated_at TIMESTAMPTZ,
  notify_template_id TEXT,
  notify_notification_id TEXT,
  notify_status TEXT,
  recipient TEXT,
  mail_merge_fields JSONB,
  domain_reference_id TEXT,
  domain_reference_type TEXT,
  log_correlation_id TEXT,
  requested_on TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  failure_reason TEXT,
  last_failed_at TIMESTAMPTZ,
  retry_count INT,
  last_send_attempt_at TIMESTAMPTZ
);