CREATE TABLE notification_library_notifications (
  id RAW(16) PRIMARY KEY,
  type VARCHAR2(4000) NOT NULL,
  status VARCHAR2(4000) NOT NULL,
  notify_template_id VARCHAR2(4000) NOT NULL,
  notify_notification_id VARCHAR2(4000),
  notify_status VARCHAR2(4000),
  notify_status_last_updated_at TIMESTAMP WITH TIME ZONE,
  recipient VARCHAR2(4000) NOT NULL,
  mail_merge_fields BLOB,
  domain_reference_id VARCHAR2(4000) NOT NULL,
  domain_reference_type VARCHAR2(4000) NOT NULL,
  log_correlation_id VARCHAR2(4000),
  requested_on TIMESTAMP WITH TIME ZONE NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE,
  failure_reason VARCHAR2(4000),
  last_failed_at TIMESTAMP WITH TIME ZONE,
  retry_count NUMBER,
  last_send_attempt_at TIMESTAMP WITH TIME ZONE,
  file_attachments BLOB
);

CREATE TABLE notification_library_notifications_aud (
  rev NUMBER(10),
  revtype NUMBER,
  id RAW(16),
  type VARCHAR2(4000),
  status VARCHAR2(4000),
  notify_status_last_updated_at TIMESTAMP WITH TIME ZONE,
  notify_template_id VARCHAR2(4000),
  notify_notification_id VARCHAR2(4000),
  notify_status VARCHAR2(4000),
  recipient VARCHAR2(4000),
  mail_merge_fields BLOB,
  domain_reference_id VARCHAR2(4000),
  domain_reference_type VARCHAR2(4000),
  log_correlation_id VARCHAR2(4000),
  requested_on TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE,
  failure_reason VARCHAR2(4000),
  last_failed_at TIMESTAMP WITH TIME ZONE,
  retry_count NUMBER,
  last_send_attempt_at TIMESTAMP WITH TIME ZONE,
  file_attachments BLOB
);