spring:
  datasource:
    url: jdbc:tc:postgresql:14.3:///test_database
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    properties:
      hibernate:
        default_schema: integration_test

  flyway:
    schemas: integration_test
    enabled: true

digital-notification-library:
  govuk-notify:
    api-key: ${INTEGRATION_TEST_GOVUK_NOTIFY_API_KEY:}
  notification:
    bulk-retrieval-limit: 2
    poll-time-seconds: 1
  mode: production