spring:
  datasource:
    url: jdbc:tc:postgresql:14.3:///test_database
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    properties:
      hibernate:
        default_schema: integration_test

  flyway:
    schemas: integration_test
    enabled: true

digital-notification-library:
  govuk-notify:
    api-key: my_test_key-26785a09-ab16-4eb0-8407-a37497a57506-3d844edf-8d35-48ac-975b-e847b4f122b0